name: SpyGame
main: com.laskdjlaskdj12.spygame.Run
version: 0.0.1
description: Spy game for Streamer
author: laskdjlaskdj12
api-version: 1.13

commands:
  start:
    description: "랜덤으로 사람들을 뽑아서 게임을 시작합니다."
    usage: /<command>
  vote:
    description: "투표를 시작합니다."
    usage: /<command>
  pickPerson:
    description: "지명 투표를 시작합니다."
    usage: /<command>
  멀린암살 :
      description: "멀린을 암살하는 시퀸스입니다."
      usage: /<command>

  #원정 커맨드
  원정:
    description: "원정 진행 커맨드입니다."
    usage: /<command>
  원정대원추가:
    description: "원정대원추가 커맨드입니다."
    usage: /<command>
  원정종료:
    description: "원정종료 커맨드입니다."
    usage: /<command>
  마차시퀸스:
    description: "마차시퀸스 커맨드입니다."
    usage: /<command>

#투표 커맨드
  투표결과공개:
    description: "원정종료 커맨드입니다."
    usage: /<command>

#라운드 커맨드
  라운드체크:
    description: "원정라운드를 보여줍니다."
    usage: /<commnad>

#디버깅용 커맨드
  투표결과:
    description: "투표결과 디버깅 커맨드입니다."
    usage: /<command>
  강제원정참여:
    description: "강제원정참여 디버깅 커맨드입니다."
    usage: /<command>
  강제캐릭터생성:
    description: "강제캐릭터생성 디버깅 커맨드입니다."
    usage: /<command>
  투표결과블록수집:
    description: "투표결과 블록수집을 하는 디버깅 커맨드입니다."
    usage: /<command>
  캐릭터정보:
    description: "모든 캐릭터 정보들을 보여주는 디버깅 커맨드입니다."
    usage: /<command>